### ISSUE TITLE
[2.0.0-beta.3] [PHP 8] Error:0 Division by zero

### ISSUE THREAD

**Issue by Bond97** [JoomShaper/helix-ultimate#158]
**Steps to reproduce issue**
1. Create 5-10 articles in test category
2. Set new menu item "test category list"
3. Set in this menu item `category blog`->`test category`
4. Go to this menu item in frontend
5. You will see this error
![изображение](https://user-images.githubusercontent.com/78050514/117809151-7f795b00-b266-11eb-8c88-ebb29d583ac6.png)

**Test environment**

![изображение](https://user-images.githubusercontent.com/78050514/117809276-a8015500-b266-11eb-84dd-03766df0e3eb.png)

**Additional information**

Issue has gone, when PHP version is 7.4.18, that's why I write in title PHP 8.

**Comment by ssnobben** [comment]
Any comments devs? ( +2 months ago today )

**Comment by mdamjadrana** [comment]
I tested it's fine in PHP 8.0.0.

**Comment by 4ndyZ** [comment]
### Steps to reproduce the issue

See op.

### Expected result

The page gets rendered without error.

### Actual result

Error page with the following stack trace.

```2021-12-26T11:07:31+00:00	CRITICAL <IP>	error	Uncaught Throwable of type DivisionByZeroError thrown with message "Division by zero". Stack trace: #0 /homepages/38/d170673535/htdocs/clickandbuilds/Joomla/KCK20/templates/shaper_helixultimate/html/com_content/category/blog.php(11): require()
#1 /homepages/38/d170673535/htdocs/clickandbuilds/Joomla/KCK20/libraries/src/MVC/View/HtmlView.php(429): include('/homepages/38/d...')
#2 /homepages/38/d170673535/htdocs/clickandbuilds/Joomla/KCK20/libraries/src/MVC/View/HtmlView.php(218): Joomla\CMS\MVC\View\HtmlView->loadTemplate(NULL)
#3 /homepages/38/d170673535/htdocs/clickandbuilds/Joomla/KCK20/libraries/src/MVC/View/CategoryView.php(268): Joomla\CMS\MVC\View\HtmlView->display(NULL)
#4 /homepages/38/d170673535/htdocs/clickandbuilds/Joomla/KCK20/components/com_content/src/View/Category/HtmlView.php(207): Joomla\CMS\MVC\View\CategoryView->display(NULL)
#5 /homepages/38/d170673535/htdocs/clickandbuilds/Joomla/KCK20/libraries/src/MVC/Controller/BaseController.php(692): Joomla\Component\Content\Site\View\Category\HtmlView->display()
#6 /homepages/38/d170673535/htdocs/clickandbuilds/Joomla/KCK20/components/com_content/src/Controller/DisplayController.php(125): Joomla\CMS\MVC\Controller\BaseController->display(false, Array)
#7 /homepages/38/d170673535/htdocs/clickandbuilds/Joomla/KCK20/libraries/src/MVC/Controller/BaseController.php(730): Joomla\Component\Content\Site\Controller\DisplayController->display()
#8 /homepages/38/d170673535/htdocs/clickandbuilds/Joomla/KCK20/libraries/src/Dispatcher/ComponentDispatcher.php(146): Joomla\CMS\MVC\Controller\BaseController->execute('display')
#9 /homepages/38/d170673535/htdocs/clickandbuilds/Joomla/KCK20/components/com_content/src/Dispatcher/Dispatcher.php(55): Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()
#10 /homepages/38/d170673535/htdocs/clickandbuilds/Joomla/KCK20/libraries/src/Component/ComponentHelper.php(389): Joomla\Component\Content\Site\Dispatcher\Dispatcher->dispatch()
#11 /homepages/38/d170673535/htdocs/clickandbuilds/Joomla/KCK20/libraries/src/Application/SiteApplication.php(206): Joomla\CMS\Component\ComponentHelper::renderComponent('com_content')
#12 /homepages/38/d170673535/htdocs/clickandbuilds/Joomla/KCK20/libraries/src/Application/SiteApplication.php(245): Joomla\CMS\Application\SiteApplication->dispatch()
#13 /homepages/38/d170673535/htdocs/clickandbuilds/Joomla/KCK20/libraries/src/Application/CMSApplication.php(278): Joomla\CMS\Application\SiteApplication->doExecute()
#14 /homepages/38/d170673535/htdocs/clickandbuilds/Joomla/KCK20/includes/app.php(63): Joomla\CMS\Application\CMSApplication->execute()
#15 /homepages/38/d170673535/htdocs/clickandbuilds/Joomla/KCK20/index.php(32): require_once('/homepages/38/d...')
#16 {main}
```

### System information (as much as possible)

Joomla! 4.0.5 Stable [ Furaha ] 11-December-2021 20:52 GMT
Helix Ultimate 2.0.5
Webserver Apache
PHP Version 8.0.13

### Additional comments

Works fine with PHP 7.4.26
